name: Package Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Package Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Node Setup
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
      - name: Setup Environment
        run: node -e "let pkg = require('./package.json'); console.log('PACKAGE_VERSION=' + pkg.version + '\nPACKAGE_NAME=' + pkg.name + '-' + pkg.version)" >> $GITHUB_ENV
      - name: Install VSCE
        run: npm install -g @vscode/vsce
      - name: Package Extension
        run: vsce package -o ./${{ env.PACKAGE_NAME }}.vsix
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            name: v${{ env.PACKAGE_VERSION }}
            draft: false
            prerelease: false
            files: ./${{ env.PACKAGE_NAME }}.vsix
